act: conti
batch_size: 64
data_dir: 1s_edge_conti128_rain50
epochs: 50000
model_dir: 60s_50k_conti_pred_useh
n_sp_layer: 5
n_tp_layer: 5
norm: true
save_gap: 1000
seq_in: 60
seq_out: 60
train: true
use_edge: true
