act: conti
agent_dir: 5s_10k_conti_mbrl_observ_sac_norough2
batch_size: 64
conv: 'False'
data_dir: ./envs/data/astlingen/1s_edge_conti128_rain50
episodes: 10000
horizon: 60
if_flood: true
mac: true
model_based: true
model_dir: 5s_20k_conti_500ledgef_res_norm_flood_gat
n_layer: 5
norm: true
processes: 4
rain_dir: ast_train50_events.csv
rain_num: 1
repeats: 2
result_dir: ./results/
save_gap: 1000
scale: 0.1
train: true
