shunqing:
  # env args
  env: shunqing
  directed: False
  length: 0
  order: 1
  graph_base: False
  rain_dir: ./envs/config/
  rain_suffix:
  rain_num: 50
  swmm_step: 1

  # simulate args
  simulate: False
  data_dir: ./envs/data/shunqing/
  train_event_id: ''
  act: 'False'
  processes: 5
  repeats: 1

  # train args
  train: False
  seed: 42
  load_model: False
  model_dir: ./model/shunqing/
  ratio: 0.8
  learning_rate: 0.001
  epochs: 500
  save_gap: 500
  batch_size: 128
  roll: 0
  mixed_precision: False
  gradnorm: False
  
  # network args
  dim: 128
  nly: 2
  kernel: 3
  seq: 6
  seq_out: 1
  if_flood: False
  epsilon: -1.0

  # predictor benchmark
  full: False
  norm: False
  vol: False
  cum: False

  # test args
  test: False
  result_dir: ./results/shunqing/
  hotstart: False

redchicosur:
  # env args
  env: redchicosur
  directed: False
  length: 0
  order: 1
  graph_base: False
  rain_dir: ./envs/config/
  rain_suffix:
  rain_num: 50
  swmm_step: 1

  # simulate args
  simulate: False
  data_dir: ./envs/data/redchicosur/
  train_event_id: ''
  act: 'False'
  processes: 5
  repeats: 1

  # train args
  train: False
  seed: 42
  load_model: False
  model_dir: ./model/redchicosur/
  ratio: 0.8
  learning_rate: 0.001
  epochs: 500
  save_gap: 500
  batch_size: 128
  roll: 0
  mixed_precision: False
  gradnorm: False
  
  # network args
  dim: 128
  nly: 2
  kernel: 3
  seq: 6
  seq_out: 1
  if_flood: False
  epsilon: -1.0

  # predictor benchmark
  full: False
  norm: False
  vol: False
  cum: False

  # test args
  test: False
  result_dir: ./results/redchicosur/
  hotstart: False

astlingen:
  # env args
  env: astlingen
  directed: False
  length: 0
  order: 1
  graph_base: False
  rain_dir: ./envs/config/
  rain_suffix:
  rain_num: 50
  swmm_step: 1

  # simulate args
  simulate: False
  data_dir: ./envs/data/astlingen/
  train_event_id: ''
  act: 'False'
  processes: 5
  repeats: 1

  # train args
  train: False
  seed: 42
  load_model: False
  model_dir: ./model/astlingen/
  ratio: 0.8
  learning_rate: 0.001
  epochs: 500
  save_gap: 500
  batch_size: 128
  roll: 0
  mixed_precision: False
  gradnorm: False
  
  # network args
  dim: 128
  nly: 2
  kernel: 3
  seq: 6
  seq_out: 1
  if_flood: False
  epsilon: -1.0

  # predictor benchmark
  full: False
  norm: False
  vol: False
  cum: False

  # test args
  test: False
  result_dir: ./results/astlingen/
  hotstart: False

hague:
  # env args
  env: hague
  directed: False
  length: 0
  order: 1
  graph_base: False
  rain_dir: ./envs/config/
  rain_suffix:
  rain_num: 50
  swmm_step: 1

  # simulate args
  simulate: False
  data_dir: ./envs/data/hague/
  train_event_id: ''
  act: 'False'
  processes: 5
  repeats: 1

  # train args
  train: False
  seed: 42
  load_model: False
  model_dir: ./model/hague/
  ratio: 0.8
  learning_rate: 0.001
  epochs: 500
  save_gap: 500
  batch_size: 128
  roll: 0
  mixed_precision: False
  gradnorm: False
  
  # network args
  dim: 128
  nly: 2
  kernel: 3
  seq: 6
  seq_out: 1
  if_flood: False
  epsilon: -1.0

  # predictor benchmark
  full: False
  norm: False
  vol: False
  cum: False

  # test args
  test: False
  result_dir: ./results/hague/
  hotstart: False

chaohu:
  # env args
  env: chaohu
  directed: False
  length: 0
  order: 1
  graph_base: False
  rain_dir: ./envs/config/
  rain_suffix:
  rain_num: 50
  swmm_step: 1

  # simulate args
  simulate: False
  data_dir: ./envs/data/chaohu/
  train_event_id: ''
  act: 'False'
  processes: 5
  repeats: 1

  # train args
  train: False
  seed: 42
  load_model: False
  model_dir: ./model/chaohu/
  ratio: 0.8
  learning_rate: 0.001
  epochs: 500
  save_gap: 500
  batch_size: 128
  roll: 0
  mixed_precision: False
  gradnorm: False
  
  # network args
  dim: 128
  nly: 2
  kernel: 3
  seq: 6
  seq_out: 1
  if_flood: False
  epsilon: -1.0

  # predictor benchmark
  full: False
  norm: False
  vol: False
  cum: False

  # test args
  test: False
  result_dir: ./results/chaohu/
  hotstart: False