shunqing:
  # env args
  env: shunqing
  directed: False
  length: 0
  order: 1
  graph_base: 0
  rain_dir: ./envs/config/
  rain_suffix: bpswmm
  rain_num: 119
  swmm_step: 1

  # simulate args
  simulate: False
  data_dir: ./envs/data/shunqing/
  train_event_id: ''
  act: 'False'
  processes: 5
  repeats: 1

  # train args
  train: False
  load_model: False
  edge_fusion: False
  use_adj: False
  model_dir: ./model/shunqing/
  ratio: 0.8
  learning_rate: 0.001
  epochs: 500
  save_gap: 500
  batch_size: 256
  roll: 0
  balance: 0
  
  # network args
  conv: GCNconv
  embed_size: 128
  n_sp_layer: 2
  dropout: 0.0
  activation: relu
  recurrent: GRU
  hidden_dim: 64
  kernel_size: 3
  n_tp_layer: 2
  seq_in: 6
  seq_out: 1
  resnet: False
  if_flood: 0
  epsilon: -1.0

  # predictor benchmark
  full: False
  norm: False
  vol: False
  cum: False

  # test args
  test: False
  result_dir: ./results/shunqing/
  hotstart: False

RedChicoSur:
  # env args
  env: RedChicoSur
  directed: False
  length: 0
  order: 1
  graph_base: 0
  rain_dir: ./envs/config/
  rain_suffix:
  rain_num: 1
  swmm_step: 1

  # simulate args
  simulate: False
  data_dir: ./envs/data/RedChicoSur/
  train_event_id: ''
  act: 'False'
  processes: 5
  repeats: 1

  # train args
  train: False
  load_model: False
  edge_fusion: False
  use_adj: False
  model_dir: ./model/RedChicoSur/
  ratio: 0.8
  learning_rate: 0.001
  epochs: 500
  save_gap: 500
  batch_size: 256
  roll: 0
  balance: 0
  
  # network args
  conv: GCNconv
  embed_size: 128
  n_sp_layer: 2
  dropout: 0.0
  activation: relu
  recurrent: GRU
  hidden_dim: 64
  kernel_size: 3
  n_tp_layer: 2
  seq_in: 6
  seq_out: 1
  resnet: False
  if_flood: 0
  epsilon: -1.0

  # predictor benchmark
  full: False
  norm: False
  vol: False
  cum: False

  # test args
  test: False
  result_dir: ./results/RedChicoSur/
  hotstart: False

astlingen:
  # env args
  env: astlingen
  directed: False
  length: 0
  order: 1
  graph_base: 0
  rain_dir: ./envs/config/
  rain_suffix:
  rain_num: 50
  swmm_step: 1

  # simulate args
  simulate: False
  data_dir: ./envs/data/astlingen/
  train_event_id: ''
  act: 'False'
  processes: 5
  repeats: 1

  # train args
  train: False
  load_model: False
  edge_fusion: False
  use_adj: False
  model_dir: ./model/astlingen/
  ratio: 0.8
  learning_rate: 0.001
  epochs: 500
  save_gap: 500
  batch_size: 256
  roll: 0
  balance: 0
  
  # network args
  conv: GCNconv
  embed_size: 128
  n_sp_layer: 2
  dropout: 0.0
  activation: relu
  recurrent: GRU
  hidden_dim: 64
  kernel_size: 3
  n_tp_layer: 2
  seq_in: 6
  seq_out: 1
  resnet: False
  if_flood: 0
  epsilon: -1.0

  # predictor benchmark
  full: False
  norm: False
  vol: False
  cum: False

  # test args
  test: False
  result_dir: ./results/astlingen/
  hotstart: False

hague:
  # env args
  env: hague
  directed: False
  length: 0
  order: 1
  graph_base: 0
  rain_dir: ./envs/config/
  rain_suffix:
  rain_num: 50
  swmm_step: 1

  # simulate args
  simulate: False
  data_dir: ./envs/data/hague/
  train_event_id: ''
  act: 'False'
  processes: 5
  repeats: 1

  # train args
  train: False
  load_model: False
  # there exists external flow to outfall, so edge_fusion donot work well
  edge_fusion: False
  use_adj: False
  model_dir: ./model/hague/
  ratio: 0.8
  learning_rate: 0.001
  epochs: 500
  save_gap: 500
  batch_size: 256
  roll: 0
  balance: 0
  
  # network args
  conv: GCNconv
  embed_size: 128
  n_sp_layer: 2
  dropout: 0.0
  activation: relu
  recurrent: GRU
  hidden_dim: 64
  kernel_size: 3
  n_tp_layer: 2
  seq_in: 6
  seq_out: 1
  resnet: False
  if_flood: 0
  epsilon: -1.0

  # predictor benchmark
  full: False
  norm: False
  vol: False
  cum: False
  
  # test args
  test: False
  result_dir: ./results/hague/
  hotstart: False

chaohu:
  # env args
  env: chaohu
  directed: False
  length: 0
  order: 1
  graph_base: 0
  rain_dir: ./envs/config/
  rain_suffix: chaohu
  rain_num: 50
  swmm_step: 1

  # simulate args
  simulate: False
  data_dir: ./envs/data/chaohu/
  train_event_id: ''
  act: 'False'
  processes: 5
  repeats: 1

  # train args
  train: False
  load_model: False
  edge_fusion: False
  use_adj: False
  model_dir: ./model/chaohu/
  ratio: 0.8
  learning_rate: 0.001
  epochs: 500
  save_gap: 500
  batch_size: 256
  roll: 0
  balance: 0
  
  # network args
  conv: GCNconv
  embed_size: 128
  n_sp_layer: 2
  dropout: 0.0
  activation: relu
  recurrent: GRU
  hidden_dim: 64
  kernel_size: 3
  n_tp_layer: 2
  seq_in: 6
  seq_out: 1
  resnet: False
  if_flood: 0
  epsilon: -1.0

  # predictor benchmark
  full: False
  norm: False
  vol: False
  cum: False

  # test args
  test: False
  result_dir: ./results/chaohu/
  hotstart: False
