astlingen:
  # env args
  env: astlingen
  directed: False
  length: 0
  order: 1
  rain_dir: ./envs/config/
  rain_suffix:
  rain_num: 50
  swmm_step: 30

  # MPC args
  sample_interval: 5
  ctrl_step: 5
  act: 'False'
  lag: False

  processes: 1
  seed: 42
  horizon: 60
  pop_size: 32
  use_current: False
  initial_dir: ./results/astlingen/
  sampling: 0.4
  crossover:
    - 1.0
    - 3.0
  mutation:
    - 1.0
    - 3.0
  termination:
    - n_eval
    - '256'
  surrogate: False
  predict: False
  model_dir: ./model/astlingen/
  batch_size: 32
  epsilon: -1.0
  gradient: False
  method: gr
  lr: 0.01
  tau: 1.0
  warm_eps: 0.01
  logit_bound: 0.1
  keep: 'False'
  stochastic: 0
  error: 0.0
  result_dir: ./results/astlingen/


hague:
  # env args
  env: hague
  directed: False
  length: 0
  order: 1
  rain_dir: ./envs/config/
  rain_suffix:
  rain_num: 50
  swmm_step: 30
  
  # MPC args
  sample_interval: 15
  ctrl_step: 15
  act: 'False'
  lag: False

  processes: 1
  seed: 42
  horizon: 60
  pop_size: 32
  use_current: False
  initial_dir: ./results/hague/
  sampling: 0.4
  crossover:
    - 1.0
    - 3.0
  mutation:
    - 1.0
    - 3.0
  termination:
    - n_eval
    - '256'
  surrogate: False
  predict: False
  model_dir: ./model/hague/
  batch_size: 32
  epsilon: -1.0
  gradient: False
  method: gr
  lr: 0.01
  tau: 1.0
  warm_eps: 0.01
  logit_bound: 0.1
  keep: 'False'
  stochastic: 0
  error: 0.0
  result_dir: ./results/hague/

chaohu:
  # env args
  env: chaohu
  directed: False
  length: 0
  order: 1
  rain_dir: ./envs/config/
  rain_suffix: chaohu
  rain_num: 50
  swmm_step: 30

  # MPC args
  sample_interval: 10
  ctrl_step: 10
  act: 'False'
  lag: False
  
  processes: 1
  seed: 42
  horizon: 60
  pop_size: 32
  use_current: False
  initial_dir: ./results/chaohu/
  sampling: 0.4
  crossover:
    - 1.0
    - 3.0
  mutation:
    - 1.0
    - 3.0
  termination:
    - n_eval
    - '256'
  keep: 'False'
  surrogate: False
  predict: False
  model_dir: ./model/chaohu/
  batch_size: 32
  epsilon: -1.0
  gradient: False
  method: gr
  lr: 0.01
  tau: 1.0
  warm_eps: 0.01
  logit_bound: 0.1
  stochastic: 0
  error: 0.0
  result_dir: ./results/chaohu/