act: rand3
agent: QMIX
agent_dir: 5s_10k_rand3_mbrl_observ_qmix_norough
batch_size: 64
conv: 'False'
data_dir: ./envs/data/
episodes: 10000
horizon: 60
<<<<<<< Updated upstream
limit: 21
=======
>>>>>>> Stashed changes
mac: true
model_based: true
model_dir: 5s_20k_conti_500ledgef_res_norm_flood_gat
n_layer: 5
norm: true
processes: 4
rain_num: 1
result_dir: ./results/
train: true
use_edge: true
