act: conti
batch_size: 64
conv: GAT
data_dir: 1s_edge_conti128_rain50
edge_fusion: true
epochs: 20000
graph_base: 1
if_flood: 3
load_model: true
model_dir: 5s_50k_conti_nodebasef_res_norm_flood_gat/retrain
n_sp_layer: 3
n_tp_layer: 3
recurrent: Conv1D
resnet: true
roll: 12
save_gap: 10000
seq_in: 5
seq_out: 5
train: true
