batch_size: 16
conv: GAT
data_dir: 1s_conti_rain50
edge_fusion: true
epochs: 20000
if_flood: 5
model_dir: 30s_20k_conti_edgef_res_flood_gat_5lyrs
n_sp_layer: 5
n_tp_layer: 5
recurrent: Conv1D
resnet: true
save_gap: 1000
seq_in: 30
seq_out: 30
train: true
