act: rand
agent_dir: 5s_10k_rand_mbfrl11_observ_sac_norough
batch_size: 32
conv: 'False'
data_dir: ./envs/data/astlingen/1s_edge_conti128_rain50
episodes: 10000
horizon: 60
if_flood: true
mac: true
model_based: true
model_dir: 5s_20k_conti_500ledgef_res_norm_flood_gat
n_layer: 5
norm: true
processes: 4
rain_dir: ast_train50_events.csv
rain_num: 1
result_dir: ./results/
sample_gap: 10
save_gap: 1000
train: true
