act: conti
batch_size: 64
conv: GAT
data_dir: 1s_edge_conti128_rain50
edge_fusion: true
epochs: 50000
if_flood: 5
length: 1.0
model_dir: 60s_try_time
n_sp_layer: 5
n_tp_layer: 5
recurrent: Conv1D
resnet: true
save_gap: 10000
seq_in: 60
seq_out: 60
train: true
