act: rand3
agent_dir: 5s_10k_rand3_mbrl_gat_sac_norough
batch_size: 64
conv: GAT
data_dir: ./envs/data/astlingen/1s_edge_conti128_rain50
episodes: 10000
graph_base: 2
horizon: 60
if_flood: 3
limit: 24
mac: true
model_based: true
model_dir: 5s_20k_conti_500ledgef_res_norm_flood_gat
n_layer: 5
norm: true
processes: 8
rain_dir: ast_train50_events.csv
rain_num: 1
result_dir: ./results/
save_gap: 1000
train: true
