act: rand3
agent_dir: 5s_10k_rand3_mbrl_observ_sac_3ly_norough_swmmstep10_disc01
batch_size: 64
data_dir: ./envs/data/astlingen/1s_edge_conti128_rain50
en_disc: 0.1
episodes: 10000
limit: 21
mac: true
model_based: true
model_dir: 5s_20k_conti_500ledgef_res_norm_flood_gat
norm: true
processes: 4
rain_dir: ast_train50_events.csv
swmm_step: 10
train: true
