act: rand3
agent_dir: 5s_10k_rand3_mbrl_observ_sac_norough
batch_size: 64
conv: 'False'
data_dir: ./envs/data/
episodes: 10000
horizon: 60
limit: 24
mac: true
model_based: true
model_dir: 5s_20k_conti_500ledgef_res_norm_flood_gat
n_layer: 5
norm: true
<<<<<<< Updated upstream
processes: 4
=======
processes: 8
rain_dir: ast_train50_events.csv
>>>>>>> Stashed changes
rain_num: 1
result_dir: ./results/
train: true
use_edge: true
