act: conti
batch_size: 64
conv: GAT
data_dir: 1s_edge_conti128_rain50
edge_fusion: true
epochs: 50000
if_flood: 3
length: 1.0
model_dir: 5s_try_time
n_sp_layer: 3
n_tp_layer: 3
recurrent: Conv1D
resnet: true
save_gap: 10000
seq_in: 5
seq_out: 5
train: true
