# Configuration file for scenario shunqing
# name of scearnio
env_name: shunqing
# if env contains actions
act: False
# time step (min)
interval: 1
# state definitions
# global state definitions
global_state:
  - !!python/tuple
    - nodes
    # - head
    - depthN
  - !!python/tuple
    - nodes
    - cuminflow
    # - totalinflow
  - !!python/tuple
    - nodes
    - totaloutflow_vol
  - !!python/tuple
    - nodes
    - cumlateralinflow
    # - lateral_inflow
  - !!python/tuple
    - links
    - depthL
  - !!python/tuple
    - links
    - volumeL
  - !!python/tuple
    - links
    - flow_vol
  - !!python/tuple
    - links
    - setting

# Key elements in loss function
loss_weight:
    
states:
  - !!python/tuple
    - RainGage
    - rainfall
  - !!python/tuple
    - jd1
    - depthN
  - !!python/tuple
    - jd2
    - depthN

# Performance Targets
performance_targets:
  - !!python/tuple
    - nodes
    - cumflooding
    - 1

flood:
  - !!python/tuple
    - nodes
    - cumflooding
    
# Rainfall scenario parameters
rainfall:
  func: split_file
  suffix: bpswmm
  filedir: ./envs/network/shunqing/
  MIET: 1
  gage: RainGage
  tide: False

# if time-variant outlet boundary
tide: False

# Model predictive parameters
prediction:
  control_horizon: 60  # Control horizon (min)
  eval_horizon: 60 # Evaluation horizon (min)
  hsf_dir: hsf # file path to save the hotstart file
  eval_dir: eval # file path to save the evaluation file
  suffix: mpc_eval_ # suffix of the evaluation file

