act: conti
batch_size: 64
conv: GAT
data_dir: 1s_edge_conti128_rain50
edge_fusion: true
epochs: 50000
if_flood: 5
model_dir: 120s_50k_conti_edgef_res_flood_gat_5lyrs
n_sp_layer: 5
n_tp_layer: 5
recurrent: Conv1D
resnet: true
save_gap: 5000
seq_in: 120
seq_out: 120
train: true
